title: "Unity でつくる SteamVR オーバーレイアプリケーション入門"
summary: |-
  SteamVR で動作するオーバーレイアプリケーションを Unity で開発するためのチュートリアルです。
  オーバーレイアプリケーションは他のアプリと同時に使用することができるため、ツールやユーティリティの作成に適しています。
  このチュートリアルでは、腕時計アプリの作成を通して、基本的な SteamVR オーバーレイアプリの作り方を紹介します。
topics: []
published: false
price: 0
allow_override: true
toc_depth: 2
chapters:
  - "introduction"
  - "create-project"
  - "initialize"
  - "create-overlay"
  - "image-file"
  - "overlay-position"
  - "relative-position"
  - "timer"
  - "dashboard"
  - "interaction"
  - "help"
  - "3d"