title: "Unity でつくる SteamVR オーバーレイアプリケーション"
summary: |-
  SteamVR オーバーレイアプリケーションを Unity で開発するためのチュートリアルです。
  オーバーレイアプリケーションは VR ゲームと同時に使用することができるため、ツールやユーティリティの作成に適しています。
  このチュートリアルでは、腕時計アプリの開発を通して、SteamVR オーバーレイアプリの基本的な作り方を紹介します。
topics: []
published: false
price: 0
allow_override: true
toc_depth: 2
chapters:
  - "introduction"
  - "create-project"
  - "initialize"
  - "create-overlay"
  - "image-file"
  - "overlay-position"
  - "relative-position"
  - "texture"
  - "dashboard1"
  - "dashboard2"
  - "controller-input"
  - "help"
