title: "Unity でつくる SteamVR オーバーレイアプリケーション"
summary: |-
  Unity で OpenVR API を使った SteamVR オーバーレイアプリを開発するためのチュートリアルです。
  オーバーレイアプリは VR ゲームと同時に起動することができるため、便利ツールの作成にぴったりです。
  このチュートリアルでは、腕時計アプリの開発を通して、SteamVR オーバーレイアプリの開発方法を紹介します。
topics: ["OpenVR", "SteamVR", "Unity", "VR", "C#"]
published: true
price: 0
allow_override: true
toc_depth: 1
chapters:
  - "introduction"
  - "create-project"
  - "initialize"
  - "create-overlay"
  - "image-file"
  - "overlay-position"
  - "relative-position"
  - "texture"
  - "dashboard1"
  - "dashboard2"
  - "controller-input"
  - "help"
